version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test and build
          command: |
            npm run test -- --coverage &&
            npm run build
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
      - save_cache:
          paths:
            - ./build/*
          key: build_folder
  public:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - restore_cache:
          keys:
            - build_folder
          name: test_return_cache
      - run:
          name: check 1
          command: ls

workflows:
  test_my_app:
    jobs:
      - build
      - public:
          requires:
            - build
